export const movies = [
    {
        movie_aid: 1,
        movie_title: "Hitman",
        movie_year: "2023",
        movie_duration: "1h 55m",
        movie_category: "KDrama",
        movie_genre: "RomCom, Comedy, Romance",
        movie_rating: "R",
        movie_summary: "A professor moonlighting as a hit man of sorts for his city police department, descends into dangerous, dubious territory when he finds himself attracted to a woman who enlists his services.",
        movie_cast: "Glen Powell, Adria Arjona, Austin Amelio",
        movie_image: "shower.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Avengers: End Game",
        movie_year: "2019",
        movie_duration: "3h 1m",
        movie_category: "International",
        movie_genre: "Action, Sci-fi",
        movie_rating: "PG-13",
        movie_summary: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        movie_cast: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
        movie_image: "assemble.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 3,
        movie_title: "The Fast and The Furious: Tokyo Drift",
        movie_year: "2006",
        movie_duration: "1h 44m",
        movie_category: "International",
        movie_genre: "Action, Crime, Car Action",
        movie_rating: "PG-13",
        movie_summary: "A teenager becomes a major competitor in the world of drift racing after moving in with his father in Tokyo to avoid a jail sentence in America.",
        movie_cast: "Lucas Black, Zachery Ty, Bryan Shad Moss",
        movie_image: "tokyo.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "Solo Leveling",
        movie_year: "2024",
        movie_duration: "24m",
        movie_category: "Anime",
        movie_genre: "Anime",
        movie_rating: "TV-MA",
        movie_summary: "Follows the adventures Sung Jinwoo in a world that is constantly threatened by monsters and the evil forces. In his battles Sung transforms himself from weakest hunter of all mankind to one of the strongest hunters in existence.",
        movie_cast: "Taito Ban, Aleks LeMin, Seung-woo",
        movie_image: "solos.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 5,
        movie_title: "How To Train Your Dragon: The Hidden World",
        movie_year: "2019",
        movie_duration: "1h 44m",
        movie_category: "International",
        movie_genre: "Teen Fantasy",
        movie_rating: "PG",
        movie_summary: "When Hiccup discovers Toothless isn't the only Night Fury, he must seek the Hidden World, a secret Dragon Utopia before a hired tyrant named Grimmel finds it first.",
        movie_cast: "Jay Baruchel, America Ferrera, F. Murray Abraham",
        movie_image: "dragons.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 6,
        movie_title: "Celebrity",
        movie_year: "2019",
        movie_duration: "1h 44m",
        movie_category: "KDrama",
        movie_genre: "Intense",
        movie_rating: "PG",
        movie_summary: "When Hiccup discovers Toothless isn't the only Night Fury, he must seek the Hidden World, a secret Dragon Utopia before a hired tyrant named Grimmel finds it first.",
        movie_cast: "Jay Baruchel, America Ferrera, F. Murray Abraham",
        movie_image: "k-1.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 7,
        movie_title: "Love Alarm",
        movie_year: "2023",
        movie_duration: "1h 55m",
        movie_category: "KDrama",
        movie_genre: "RomCom, Comedy, Romance",
        movie_rating: "R",
        movie_summary: "A professor moonlighting as a hit man of sorts for his city police department, descends into dangerous, dubious territory when he finds himself attracted to a woman who enlists his services.",
        movie_cast: "Glen Powell, Adria Arjona, Austin Amelio",
        movie_image: "k2.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 8,
        movie_title: "Goblin",
        movie_year: "2006",
        movie_duration: "1h 44m",
        movie_category: "KDrama",
        movie_genre: "Romance",
        movie_rating: "PG-13",
        movie_summary: "A goblin who is cursed to live forever and the high school student who is destined to end his suffering",
        movie_cast: "Gong Yoo, a Kim Go-eun, Lee Dong-wook, Yoo In-na, Yook Sung-jae.",
        movie_image: "k-3.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 9,
        movie_title: "The Title That I Dont Know",
        movie_year: "2019",
        movie_duration: "1h 44m",
        movie_category: "KDrama",
        movie_genre: "Teen Fantasy",
        movie_rating: "PG",
        movie_summary: "When Hiccup discovers Toothless isn't the only Night Fury, he must seek the Hidden World, a secret Dragon Utopia before a hired tyrant named Grimmel finds it first.",
        movie_cast: "Jay Baruchel, America Ferrera, F. Murray Abraham",
        movie_image: "k-4.jpg",
        movie_is_active: true,
    },
    {
        movie_aid: 10,
        movie_title: "Love Like A KDrama",
        movie_year: "2024",
        movie_duration: "24m",
        movie_category: "KDrama",
        movie_genre: "Anime",
        movie_rating: "TV-MA",
        movie_summary: "Follows the adventures Sung Jinwoo in a world that is constantly threatened by monsters and the evil forces. In his battles Sung transforms himself from weakest hunter of all mankind to one of the strongest hunters in existence.",
        movie_cast: "Taito Ban, Aleks LeMin, Seung-woo",
        movie_image: "k-5.jpg",
        movie_is_active: true,
    },
]